version: "3"
services:
  protype:
    image: protype_env:latest
    volumes:
      - /home/zhihui/workspace/protype:/project
      - /home/zhihui/workspace/protype/build:/build
    networks:
      - default
networks:
  default:
    driver: bridge